from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from enum import Enum
from datetime import datetime

class ArtifactType(str, Enum):
    DOCUMENT_ROOT = "Document_Root"
    SECTION = "Section"
    PARAGRAPH = "Paragraph"
    TABLE = "Table"

class AmbiguityStrategy(str, Enum):
    EMIT_MULTIPLE_OBSERVATIONS = "EmitMultipleObservations"
    EMIT_COMPETING_ASSERTIONS = "EmitCompetingAssertions"
    REQUEST_HUMAN_REVIEW = "RequestHumanReview"
    ABORT_EXTRACTION = "AbortExtraction"

class ConfidenceMethod(str, Enum):
    EXACT_MATCH = "ExactMatch"
    HEADER_PRIORITY = "HeaderPriority"
    TABLE_PRIORITY = "TablePriority"
    MULTIPLE_CONFIRMATION = "MultipleConfirmation"
    LLM_INFERENCE = "LLM_Inference"

# ==========================================
# 1. PHYSICAL / BASE LAYERS
# ==========================================
class Artifact(BaseModel):
    artifact_id: str
    event_id: str
    artifact_type: ArtifactType
    source_uri: str
    content_hash: str

class ObservationNode(BaseModel):
    """Pure Sensory Footprint: 'I saw these words right here'."""
    observation_id: str
    event_id: str
    artifact_id: str
    char_start: int
    char_end: int
    raw_text: str
    extracted_at: datetime = Field(default_factory=datetime.now)

# ==========================================
# 2. EPISTEMIC COEXISTENCE LAYERS
# ==========================================
class CandidateAssertion(BaseModel):
    """Pre-validated, unlinked assertion proposal."""
    candidate_id: str
    event_id: str
    schema_id: str
    object_id: str
    value_payload: Dict[str, Any]
    basis_observations: List[str]
    confidence_method: ConfidenceMethod
    extractor_profile_id: str

class KnowledgeAssertion(BaseModel):
    """The promoted, schema-validated, immutable fact asset."""
    assertion_id: str
    event_id: str
    schema_id: str
    object_id: str
    created_at: datetime = Field(default_factory=datetime.now)

class AssertionRevision(BaseModel):
    """The active state timeline wrapper for an active Assertion."""
    revision_id: str
    assertion_id: str
    value_payload: Dict[str, Any]
    justified_by_candidates: List[str]
    confidence_score: float
    valid_from: datetime = Field(default_factory=datetime.now)
    valid_to: Optional[datetime] = None
    is_active: bool = True

# ==========================================
# 3. GRAPH EDGES & RESOLUTIONS
# ==========================================
class NodeReference(BaseModel):
    node_class: str
    node_id: str

class GraphEdge(BaseModel):
    """Generated by the Linker layer."""
    edge_id: str
    event_id: str
    relationship_id: str
    source: NodeReference
    target: NodeReference
    justified_by_assertions: List[str]
    created_at: datetime = Field(default_factory=datetime.now)

# ==========================================
# 4. QUANTITATIVE LAYER & PROVENANCE
# ==========================================
class CalculationResult(BaseModel):
    """First-class model for deterministic auditability."""
    result_value: Any
    input_object_ids: List[str]
    input_hash: str
    implementation_version: str
    execution_time_ms: float
    calculated_at: datetime = Field(default_factory=datetime.now)
