import os
import sys
from src.alerts.email import send_alert

def main():
    print("[TEST EMAIL] Triggering test email dispatch via SSR alert pipeline...")
    
    # Verify environment variables are present
    recipient = os.environ.get("ALERT_EMAIL_RECIPIENT")
    smtp_server = os.environ.get("SMTP_SERVER")
    
    if not recipient or not smtp_server:
        print("[WARNING] SMTP environment variables or ALERT_EMAIL_RECIPIENT are missing. Script will run in mock print mode.")

    try:
        send_alert(
            article_title="SSR Pipeline Test Notification",
            article_url="https://github.com/tonyfonda-eng/SSR",
            event_family="SYSTEM TEST",
            confidence=100,
            research_summary=(
                "1. Executive Summary\n"
                "This is a verified test notification generated by the SSR Test Email workflow "
                "to confirm that SMTP authentication and transport layers are fully operational.\n\n"
                "4. Investment Facts\n"
                "- Transport Protocol: STARTTLS\n"
                "- Pipeline Status: Operational"
            ),
            evidence_log=[
                "Test Rule Matched: Manual Workflow Dispatch", 
                "SMTP Socket Timeout: Armed (10.0s)"
            ],
            is_update=False
        )
        print("[TEST EMAIL] Test dispatch script completed successfully.")
    except Exception as e:
        print(f"[TEST EMAIL ERROR] Failed to execute test dispatch: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()